scrape_configs:
- job_name: node_exporter
  scrape_interval: 5s
  static_configs:
  - targets:
    - node-exporter:9100
- job_name:  gateway-service
  scrape_interval: 5s
  static_configs:
  - targets:
    -  gateway-service:5000








    