FROM python:3-stretch

WORKDIR /app

#Copy the current directory into the container directory.
COPY . /app

#Install dependencies
RUN pip install --trusted-host pypi.python.org -r requirements.txt

ENV FLASK_APP=gateway.py

ENV FLASK_RUN_HOST=0.0.0.0
#Server will reload itself on file changes if in dev mode

ENV FLASK_ENV=development 

EXPOSE 5000

CMD ["flask", "run"]






